version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
  pre_build:
    commands:
      # - apt-get update -y
      # - apt-get install -y maven
      - java -version
      - pip install awscli --upgrade --user
      - echo Logging in to Amazon ECR...
      - aws --version
      - sudo apt-get install gnupg
      - wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | sudo apt-key add -
      - echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.2.list
      - sudo apt-get update
      - sudo apt-get install -y mongodb-org
      - $(aws ecr get-login --region ${region} --no-include-email)
      - REPOSITORY_URI=${repository_url}
      - CONTAINER_NAME=${container_name}
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)
      - IMAGE_URI=$REPOSITORY_URI:$IMAGE_TAG
      - mvn clean install
  build:
    commands:
      - echo Build started on `date`
      - echo $IMAGE_URI
      # - mvn clean package 
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - printenv
      - echo Build completed on `date`
      - echo $(docker images)
      - echo Pushing docker image
      - docker push $IMAGE_URI
      - echo push completed
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $IMAGE_URI > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json

cache:
  paths:
    - '/root/.m2/**/*'